// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketTVD.Services.CategoryAPI.Data;

#nullable disable

namespace TicketTVD.Services.CategoryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231102181456_AddCategoryMigration")]
    partial class AddCategoryMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketTVD.Services.CategoryAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(677),
                            Name = "Âm nhạc",
                            UpdatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(691)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(693),
                            Name = "Thể thao",
                            UpdatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(693)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(695),
                            Name = "Hội họa",
                            UpdatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(695)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(696),
                            Name = "Doanh nghệp",
                            UpdatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(697)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(698),
                            Name = "Nhiếp ảnh",
                            UpdatedAt = new DateTime(2023, 11, 3, 1, 14, 56, 208, DateTimeKind.Local).AddTicks(698)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
