// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketTVD.Services.CategoryAPI.Data;

#nullable disable

namespace TicketTVD.Services.CategoryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketTVD.Services.CategoryAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#264653",
                            CreatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(342),
                            Name = "Âm nhạc",
                            UpdatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(355)
                        },
                        new
                        {
                            Id = 2,
                            Color = "#2a9d8f",
                            CreatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(357),
                            Name = "Thể thao",
                            UpdatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(357)
                        },
                        new
                        {
                            Id = 3,
                            Color = "#e9c46a",
                            CreatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(358),
                            Name = "Hội họa",
                            UpdatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(359)
                        },
                        new
                        {
                            Id = 4,
                            Color = "#f4a261",
                            CreatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(360),
                            Name = "Doanh nghệp",
                            UpdatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(360)
                        },
                        new
                        {
                            Id = 5,
                            Color = "#e76f51",
                            CreatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(361),
                            Name = "Nhiếp ảnh",
                            UpdatedAt = new DateTime(2023, 12, 9, 1, 57, 34, 126, DateTimeKind.Local).AddTicks(362)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
